#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

# production image
docker tag $TAG_SHA $TAG_BRANCH
docker push $TAG_BRANCH
# development image
docker tag $TAG_DEV_SHA $TAG_DEV_BRANCH
docker push $TAG_DEV_BRANCH

if [ $GIT_BRANCH == "main" ]; then
   docker tag $TAG_SHA $TAG_LATEST
   docker push $TAG_LATEST
fi