#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

NETWORK=beebop_nw
VOLUME=beebop-storage
NAME_REDIS=beebop-redis
NAME_API=beebop-py-api
NAME_WORKER=beebop-py-worker

docker volume create $VOLUME
docker run --rm -v $VOLUME:/beebop/storage $TAG_SHA \
       ./scripts/download_db --small storage
docker network create $NETWORK > /dev/null || /bin/true

docker run -d --rm --name $NAME_REDIS --network=$NETWORK redis:5.0
docker run -d --rm --name $NAME_WORKER --network=$NETWORK \
       --env=REDIS_HOST="$NAME_REDIS" \
       -v $VOLUME:/beebop/storage \
       $TAG_SHA rqworker
docker run -d --rm --name $NAME_API --network=$NETWORK \
       --env=REDIS_HOST="$NAME_REDIS" \
       --env=STORAGE_LOCATION="./storage" \
       --env=DB_LOCATION="./storage/GPS_v4_references" \
       -v $VOLUME:/beebop/storage \
       -p 5000:5000 \
       $TAG_SHA
