#!/usr/bin/env bash
set -e

# TODO: need to host all dbs in 1 place (https://mrcdata.dide.ic.ac.uk/beebop  maybe?)
DEST=storage
BASE_URL=https://gps-project.cog.sanger.ac.uk
FILENAME=GPS_v8_ref.tar.gz
DEST_DIR=$DEST/GPS_v8_ref
SUFFIX=tar.gz


if [ -d "$DEST_DIR" ]; then
    echo "Database already exists at $DEST"
    echo "To redownload, please remove $DEST_DIR and run $0 again"
    exit 0
fi

echo "Downloading $FILENAME"

URL=$BASE_URL/$FILENAME
DBBZ2=$(mktemp).${SUFFIX}
wget  --progress=dot:giga $URL -O $DBBZ2
echo "Unpacking to $DEST"
mkdir -p $DEST

(cd $DEST && tar -xf $DBBZ2 && rm -f $DBBZ2)
