#!/usr/bin/env bash
set -e

USAGE="Usage: $0 [--small] [<dest>]"

SMALL=0
DEST=

while [[ $# -gt 0 ]]; do
    case $1 in
        --small)
            SMALL=1
            shift
            ;;
        -*|--*)
            echo "Unknown option $1"
            echo $USAGE
            exit 1
            ;;
        *)
            if [ ! -z $DEST ]; then
                echo "Too many positional arguments"
                echo $USAGE
                exit 1
            fi
            DEST=$1
            shift
            ;;
    esac
done

if [ -z $DEST ]; then
    DEST=storage
fi

if [ $SMALL == 0 ]; then
    BASE_URL=https://gps-project.cog.sanger.ac.uk
    FILENAME=GPS_v6.zip
    DEST_DIR=$DEST/GPS_v6
    SUFFIX=zip
else
    BASE_URL=https://mrcdata.dide.ic.ac.uk/beebop
    FILENAME=GPS_v6_references.tar.bz2
    DEST_DIR=$DEST/GPS_v6_references
    SUFFIX=tar.bz2
fi

if [ -d "$DEST_DIR" ]; then
    echo "Database already exists at $DEST"
    echo "To redownload, please remove $DEST_DIR and run $0 again"
    exit 0
fi

echo "Downloading $FILENAME"

URL=$BASE_URL/$FILENAME
DBBZ2=$(mktemp).${SUFFIX}
wget  --progress=dot:giga $URL -O $DBBZ2
echo "Unpacking to $DEST"
mkdir -p $DEST

function extract() {
    if [ $SMALL == 0 ]; then
      unzip $DBBZ2
    else
      tar -xf $DBBZ2
    fi
}

(cd $DEST && extract && rm -f $DBBZ2)
