#!/usr/bin/env bash
set -e

docker pull redis
docker run --rm -d --name=redis -p 6379:6379 redis

function cleanup() {
    docker stop redis
}
trap cleanup INT
trap cleanup ERR

rqworker & FLASK_APP=beebop/app.py poetry run flask run
