#!/usr/bin/env bash
set -e

docker pull redis
docker run --rm -d --name=redis -p 6379:6379 redis

function cleanup() {
    docker stop redis
}
trap cleanup INT
trap cleanup ERR

rq worker & STORAGE_LOCATION=./storage DB_LOCATION=./storage/GPS_v8_ref FLASK_APP=beebop/app.py poetry run flask run
