#!/usr/bin/env bash
set -e

docker pull redis
docker run --rm -d --name=redis -p 6379:6379 redis
npm install pm2

node ./node_modules/pm2/bin/pm2 --name rqworker start "/usr/share/miniconda/bin/rqworker" --interpreter python3 
